### ISSUE TITLE
ui not working properly on smapi android version

### ISSUE THREAD

**Issue by braxsis** [aEnigmatic/StardewValley#12]
when using the mod on smapi Andriod the buttons aren't where there suppose to be and menus are slightly off-screen

**Comment by firereverie** [comment]
I also have this issue with menu drawing on SDV 1.4.5.151, SMAPI 3.7.6.1 ZaneYork Installer 3.7.6.9, on a Samsung Note 9 2960x1440. Buttons draw over top of the chest inventory and the catagory selection is offset to the left and blank aside from tooltips.
