### ISSUE TITLE
Mutiplayer problem

### ISSUE THREAD

**Issue by Akylapatricio** [aEnigmatic/StardewValley#14]
Playing in multiplayer mode, I could see a problem. Basically the defined categories, start to be restarted, I still don't understand the pattern, if it is when the host interacted, or the day changes.
PS: It doesn't happen with all the chests at once, it happens little by little.

**Comment by razza-guhl** [comment]
Same here. When the game restarts (reloads a savegame) the selected categories on the farmhand player are deselected. On the host it's fine.

But the categories are still active and working on farmhands, but not visible selected. Auto-stash ("q") still works, global stash ("z") do not work.
