### ISSUE TITLE
Cursor inaccurate?

### ISSUE THREAD

**Issue by thelunarmaiden** [aEnigmatic/StardewValley#21]
whenever i select to categorise a chess, it doesn't not select the item i am hovering over. it has certain points where it would but when i hover on the centre of the item it selects the item next to it instead of the one i would like to select.

**Comment by Canbert** [comment]
Noticed this as well. Tried changing my zoom level, at 100% it works fine, but if it's higher or lower it seems to break.

**Comment by aEnigmatic** [comment]
Sorry for the inactivity, fixed with 1.6.2 :)
