### ISSUE TITLE
Some items are in no category

### ISSUE THREAD

**Issue by SolidTux** [aEnigmatic/StardewValley#23]
Maybe I'm missing them, but I can't find some items like the _Oil Maker_, _Seed Maker_ and the _Chests_ in any category (also in the last update the hat category seems to be merged with miscellaneous).

**Comment by aEnigmatic** [comment]
Fixed with f2e636d8fbe857e944e1f11efad508b92bfff9e8.  
Chests are under Crafting, Oil Maker etc under Machines & Hats under Hats.
